name = "GameZero"
uuid = "9da27670-f782-11e9-1da1-f53579315bfe"
authors = ["Avik Sengupta", "Ahan Sengupta"]
version = "0.4.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SimpleDirectMediaLayer = "98e33af6-2ee5-5afd-9e75-cbc738b767c4"

[compat]
Colors = "0.10, 0.11, 0.12, 0.13"
SimpleDirectMediaLayer = "0.3, 0.4, 0.5"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
