name = "GameZero"
uuid = "9da27670-f782-11e9-1da1-f53579315bfe"
authors = ["Avik Sengupta"]
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SimpleDirectMediaLayer = "98e33af6-2ee5-5afd-9e75-cbc738b767c4"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
